<?php

/**
 *  SFW2 - SimpleFrameWork
 *
 *  Copyright (C) 2019  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */

?>
<?php if(isset($this->title)): ?>
<h1><?php echo($this->title); ?></h1>
<?php endif; ?>
<?php if($this->permission->createAllowed()): ?>
<form id="<?php echo($this->getPathSimplified()); ?>" class="noshow">
    <div class="row">
        <label for="title" class="col-sm-2 col-form-label">Überschrift</label>
        <div class="col-sm-4">
            <input
                type="text"
                class="form-control form-control-sm"
                placeholder="Gib hier bitte die Überschrift ein..."
                name="title"
                value=""
                title="Gib hier bitte eine Überschrift ein."
                maxlength="100"
            />
            <div class="invalid-feedback"></div>
        </div>
    </div>
    <div class="row">
        <label for="content" class="col-sm-2 col-form-label">Inhalt</label>
        <div class="col-sm-8">
            <textarea
                id="<?php echo($this->getPathSimplified()); ?>_area"
                style="height: 10rem"
                class="form-control form-control-sm"
                placeholder="Gib hier bitte den Inhalt ein..."
                data-name="content"
                title="Gib hier bitte den Inhalt ein."
            ></textarea>
            <div class="invalid-feedback"></div>
        </div>
    </div>
</form>
<?php endif; ?>
<div class="reload-data" data-url="<?php echo($this->getCurrentPath()); ?>" >
</div>
