<?php

/**
 *  SFW2 - SimpleFrameWork
 *
 *  Copyright (C) 2017  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */

?>
<h1><?php echo($this->title); ?></h1>
<?php if($this->file == ''): ?>
<div class="alert alert-info mt-5" role="alert"><strong>Anmerkung:</strong><p>Im Moment gibt's nichts Neues zu berichten!</p></div>
<?php else: ?>
<div class="container">
    <div class="row">
        <?php if($this->link == ''): ?>
        <img class="content-image rounded float-left mb-2" alt="" src="/<?php echo($this->file); ?>">
        <?php else: ?>
        <a href="<?php echo($this->link); ?>" target="_blank">
            <img class="content-image rounded float-left mb-2" alt="" src="/<?php echo($this->file); ?>">
        </a>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<?php if($this->permission->createAllowed()): ?>
<form id="<?php echo($this->getPathSimplified()); ?>" class="noshow">
    <div class="row">
        <label for="title" class="col-sm-2 col-form-label">Überschrift</label>
        <div class="col-sm-7">
            <input
                type="text"
                class="form-control form-control-sm"
                placeholder="Gib hier bitte die Überschrift ein..."
                name="title"
                value=""
                title="Gib hier bitte eine Überschrift ein."
                maxlength="100"
            />
            <div class="invalid-feedback"></div>
        </div>
    </div>
    <div class="row">
        <label for="title" class="col-sm-2 col-form-label">Link</label>
        <div class="col-sm-7">
            <input
                type="text"
                class="form-control form-control-sm"
                placeholder="Gib hier bitte einen Hyperlink an..."
                name="link"
                value=""
                title="Gib hier bitte einen Hyperlink an."
                maxlength="100"
            />
            <div class="invalid-feedback"></div>
        </div>
    </div>
    <div class="row">
        <label for="newspaper" class="col-sm-2 col-form-label">Bild / PDF</label>
        <div class="col-sm-7">
            <div class="fileupload">

                <!-- FIXME --- 8x ---- 8x --- !-->

                <div class="custom-file">
                    <input
                        data-onlyimage="false" type="file" class="custom-file-input" id="customFile"
                        accept="image/jpeg,image/png,image/gif,image/bmp,image/webp,image/tiff,application/pdf"
                    >
                    <div class="invalid-feedback"></div>
                    <label class="custom-file-label" for="customFile">Datei auswählen</label>
                </div>

                <script>
                $(document).ready(function () {
                    bsCustomFileInput.init();
                });
                </script>
                <div class="noshow progress mt-2">
                    <div id="progressbar-file" class="progress-bar progress-bar-striped bg-success progress-bar-animated" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
                </div>

                    <?php /*
                <div class="dropzone">
                    <a class="btnRemove noshow" href="#">x</a>
                    <div id="fileSelectDescr_">
                        <?php if(false && $this->multiple): ?>
                        Dateien hier ablegen
                        <?php else: ?>
                        Datei hier ablegen
                        <?php endif; ?>
                    </div>
                    <div id="clearFileSelect_" class="noshow">
                        <input
                            class="fileselectupload"
                            type="file"
                            name="file"
                            <?php if(false && $this->multiple): ?>
                            multiple="multiple"
                            <?php endif; ?>
                            style="width: 24em;"
                        />
                    </div>
                    <div class="currfile"></div>
                </div>
*/ ?>
                <!-- 8x ---- 8x --- !-->

            </div>
        </div>
    </div>
</form>
<button
    type="button"
    class="btn btn-success btn-sm"
    data-toggle="modal"
    data-target="#createDialogModal"
    data-url="<?php echo($this->getCurrentPath()); ?>"
    data-form-id="<?php echo($this->getPathSimplified()); ?>"
>bearbeiten</button>
<?php endif; ?>
<?php if($this->file != ''): ?>
<?php if($this->permission->deleteAllAllowed()): ?>
<button
    type="button"
    class="btn btn-danger btn-sm"
    data-toggle="modal"
    data-target="#deleteDialogModal"
    data-url="<?php echo($this->getCurrentPath()); ?>"
    data-item-id="<?php echo($this->id); ?>"
    data-form-id="<?php echo($this->getPathSimplified()); ?>"
>löschen</button>
<?php endif; ?>
<div class="modificationDate mt-5">
    <small class="blogheader">
        Zuletzt bearbeitet von <?php echo($this->author);?> am <time pubdate="pubdate"><?php echo($this->date);?></time>
    </small>
</div>
<?php endif; ?>
